name: Delete Workflow Runs
on:
  workflow_dispatch:

jobs:
  delete-dmg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete DMG Workflow Runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.1.0
        with:
          repository: Comp-Labs/Download-macOS
          workflow: ".github/workflows/dmg.yml"
          status: completed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  delete-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete ISO Workflow Runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.1.0
        with:
          repository: Comp-Labs/Download-macOS
          workflow: ".github/workflows/iso.yml"
          status: completed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  delete-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete ZIP Workflow Runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.1.0
        with:
          repository: Comp-Labs/Download-macOS
          workflow: ".github/workflows/zip.yml"
          status: completed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
