name: List Available macOS Releases

on:
  workflow_dispatch:

jobs:
  list-installers:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: List Installers
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate
          softwareupdate --list-full-installers
