name: List Available macOS Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
 list-installers:
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v3
    - name: List Installers
      run: |
        sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
        sleep 5
        softwareupdate
        softwareupdate --list-full-installers
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp-mail.outlook.com
        server_port: 587
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Weekly macOS List Installers Report
        to: complabs28@gmail.com
        from: GitHub Reports <github.reports@complabs.in>
        secure: true
        body: ${{github.job}} Job completed successfully! # https://github.com/Comp-Labs/Download-macOS/commit/${github.commit.sha}/checks/${run_id}/logs
        html_body: file://README.html
        reply_to: complabs28@gmail.com
        ignore_cert: true
        convert_markdown: true  
