name: List Available macOS Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  list-installers:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: List Installers
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate
          softwareupdate --list-full-installers
      - name: Send mail
        env:
          COMMIT_SHA: ${{github.sha}}
          RUN_ID: ${{github.run_id}}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: email-smtp.ap-south-1.amazonaws.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Weekly macOS List Installers Report
          to: complabs28@gmail.com
          from: GitHub Reports <github.reports@complabs.in>
          secure: true
          body: ${{github.job}} Job Status is ${{job.status}}! **Logs Available At** - https://github.com/Comp-Labs/Download-macOS/commit/${github.commit.sha}/checks/${run_id}/logs
          reply_to: complabs28@gmail.com
          ignore_cert: true
          convert_markdown: true
  re-run-failed-jobs:
    runs-on: ubuntu-latest
    needs: [build-iso]
    if: always() && (needs.build-iso.result == 'failure')
    steps:
      - name: Needs Context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: echo "$NEEDS_CONTEXT"
