# This is a basic workflow to help you get started with Actions

name: DownloadVentura

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download macOS Ventura Latest
        run: |
           sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
           sleep 5
           softwareupdate --fetch-full-installer --full-installer-version 13.0
      - name: Upload macOS from Root
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Ventura
          path: "/Applications/Install macOS 13 Beta.app"
      - name: Upload macOS from Home
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Ventura
          path: "~/Applications/Install macOS 13 Beta.app"
