name: Generate ZIP

on:
  workflow_dispatch:
    inputs:
      macos_version:
        type: choice
        description: "macOS Version"
        required: true
        options:
          - Monterey v12.4
          - Big Sur v11.6.8
          - Catalina v10.15.7
          - Mojave v10.14.6
          - High Sierra v10.13.6
          - Ventura Beta v13.0
          - Monterey Beta v12.5

jobs:
  build-zip:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # MARK: macOS Version

      - if: github.event.inputs.macos_version == 'Monterey v12.4'
        name: Download macOS Monterey Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 12.4

      - if: github.event.inputs.macos_version == 'Big Sur v11.6.8'
        name: Download macOS BigSur Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 11.6.8

      - if: github.event.inputs.macos_version == 'Catalina v10.15.7'
        name: Download macOS Catalina Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 10.15.7

      - if: github.event.inputs.macos_version == 'Mojave v10.14.6'
        name: Download macOS Mojave Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 10.14.6

      - if: github.event.inputs.macos_version == 'High Sierra v10.13.6'
        name: Download macOS HighSierra Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 10.13.6

      - if: github.event.inputs.macos_version == 'Ventura Beta v13.0'
        name: Download macOS Ventura Beta Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 13.0

      - if: github.event.inputs.macos_version == 'Monterey Beta v12.5'
        name: Download macOS MontereyBeta Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 12.5
      
            # Monterey

      - if: github.event.inputs.macos_version == 'Monterey v12.4'
        name: ZIP and Upload
        run: |
          cd /Applications
          zip -r "Install macOS Monterey.zip" "Install macOS Monterey.app"
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Monterey
          path: "/Applications/Install macOS Monterey.zip"

      # Big Sur

      - if: github.event.inputs.macos_version == 'Big Sur v11.6.8'
        name: ZIP and Upload
        run: |
          cd /Applications
          zip -r "Install macOS Big Sur.zip" "Install macOS Big Sur.app"
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Big Sur
          path: "/Applications/Install macOS Big Sur.zip"

      # Catalina

      - if: github.event.inputs.macos_version == 'Catalina v10.15.7'
        name: ZIP and Upload
        run: |
          cd /Applications
          zip -r "Install macOS Catalina.zip" "Install macOS Catalina.app"
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Catalina
          path: "/Applications/Install macOS Catalina.zip"

      # Mojave

      - if: github.event.inputs.macos_version == 'Mojave v10.14.6'
        name: ZIP and Upload
        run: |
          cd /Applications
          zip -r "Install macOS Mojave.zip" "Install macOS Mojave.app"
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Mojave
          path: "/Applications/Install macOS Mojave.zip"

      # High Sierra

      - if: github.event.inputs.macos_version == 'High Sierra v10.13.6'
        name: ZIP and Upload
        run: |
          cd /Applications
          zip -r "Install macOS High Sierra.zip" "Install macOS High Sierra.app"
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS High Sierra
          path: "/Applications/Install macOS High Sierra.zip"

      # Ventura Beta

      - if: github.event.inputs.macos_version == 'Ventura Beta v13.0'
        name: ZIP and Upload
        run: |
          cd /Applications
          zip -r "Install macOS 13 Beta.zip" "Install macOS 13 Beta.app"
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Ventura Beta
          path: "/Applications/Install macOS 13 Beta.zip"

      # Monterey Beta

      - if: github.event.inputs.macos_version == 'Monterey Beta v12.5'
        name: ZIP and Upload
        run: |
          cd /Applications
          ls
          zip -r "Install macOS 12 Beta.zip" "Install macOS 12 Beta.app"
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Monterey Beta
          path: "/Applications/Install macOS 12 Beta.zip"
